### ISSUE TITLE
Split Variant into its own package?

### ISSUE THREAD

**Issue by woehr** [haskus/haskus-utils#1]
I discovered Variant from http://hsyl20.fr/home/posts/2018-05-22-extensible-adt.html and am going to be experimenting with it. However, it would be nice to be able to use it without getting all of the other things in haskus-utils.

**Comment by hsyl20** [comment]
I have just split the package into 4 packages. The new `haskus-utils-variant` package has much less dependencies.

**Comment by woehr** [comment]
Thanks!
