### ISSUE TITLE
Left / Right of popVariantF/splitVariantF

### ISSUE THREAD

**Issue by pcarbonn** [haskus/haskus-utils#10]
In popVariantF, the selected constructor is on Right, while in splitVariantF, they are in Left...  

It would be more consistent to have them on the same side (but that would be a breaking change)...

**Comment by hsyl20** [comment]
Tests revealed a nasty bug in splitVariant[F]. It is fixed by 36be8af41947cbef196c038ae23a4cd62e837c28. I switched Left/Right results at the same time. Release 2.2 contains the fix.
