### ISSUE TITLE
no per-module documentation on Hackage

### ISSUE THREAD

**Issue by pcarbonn** [haskus/haskus-utils#12]
Since release 2.0.2, the haddock-generated documentation of each module of haskus-utils-variant is not available [on hackage](https://hackage.haskell.org/package/haskus-utils-variant-2.0.2) anymore: e.g. [EADT](https://hackage.haskell.org/package/haskus-utils-variant-2.0.2/docs/Haskus-Utils-EADT.html).

Same for [haskus-utils-types-1.2](https://hackage.haskell.org/package/haskus-utils-types)

**Comment by hsyl20** [comment]
Hackage just switched to ghc-8.6 to build the docs, hence it fails with the automatic upper bound added to `base` by stack when uploading with `--pvp-bounds both` (see https://hackage.haskell.org/package/haskus-utils-types-1.2/reports/3).

I've added explicit upper bounds in c70dcc46bbab3c232c9bc3cbefa2a9fa33ed6e69. I'll make Hackage revisions and trigger the doc rebuilding.

**Comment by hsyl20** [comment]
Upstream issue: https://github.com/haskell/hackage-server/issues/515

**Comment by hsyl20** [comment]
Docs for the new releases are generated correctly thanks to the correct base upper bound.
