### ISSUE TITLE
Size of the Variant type?

### ISSUE THREAD

**Issue by wpoosanguansit** [haskus/haskus-utils#17]
Hi,

I am trying out the Variant code and I am curious if there is a way to check the size of the Variant types, not the size of the value.

for v :: V '[A, B, C, D] I would like to to get the size of 4 out.  Thank you for your help.

**Comment by hsyl20** [comment]
Hi,

You can do it as follows:

```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE ScopedTypeVariables #-}

import Haskus.Utils.Variant
import Haskus.Utils.Types
import Haskus.Utils.Types.List

variantSize :: forall xs. (KnownNat (Length xs)) => V xs -> Word
variantSize _ = natValue @(Length xs)
```

Test:

```haskell
> data A
> data B
> data C
> data D
> let v = undefined :: V '[A,B,C,D]
> variantSize v
4
```

**Comment by hsyl20** [comment]
You're welcome. As it can be useful to others, I've added it for the next release.
