### ISSUE TITLE
Extensible Parser ?

### ISSUE THREAD

**Issue by pcarbonn** [haskus/haskus-utils#4]
I'm going to use EADTs in a transpiler in front of a constraint solver.  I love the idea of starting with a small constraint language, and adding new features to the language progressively: with EADT, it will be easy to add typecheck, annotate, transform and reduce steps for each new feature.

What is not clear to me is how to design an extensible Parser (e.g. using megaparsec), i.e. how to extend the parser with each new language construct.  Could you elaborate on that, and update the documentation if appropriate ?

Thanks in advance.

**Comment by wiz** [comment]
I did that with `megaparsec`. You just collect your parser compoments into groups where appropriate. You can even fiddle with type classes later, but utility of such a design is to be decided.

**Comment by pcarbonn** [comment]
Thanks. I'll give it a try.

**Comment by pcarbonn** [comment]
I have now written a [showcase of EADT](https://github.com/pcarbonn/H-Calc), including an extensible parser. (any feedback welcome)

You may want to update the documentation of Haskus to refer to it.

**Comment by pcarbonn** [comment]
(Also, I would call it `eadtPattern`, instead of `eadtPat`, for increased readability.)

**Comment by hsyl20** [comment]
> I would be happy to use `eadtPat` and `algVariantF`, but I cannot find them (nor their documentation) in `haskus-utils-variant-1.0`, nor in any other package on hackage. Pls provide pointers.

I have just uploaded a new release to Hackage: haskus-utils-variant-2.0

> (Also, I would call it `eadtPattern`, instead of `eadtPat`, for increased readability.)

Indeed! Fixed too. Thanks for the feedback.
